from setuptools import setup, find_packages

setup(
    name="apmti",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "scipy>=1.7.0",
        "scikit-learn>=0.24.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "pytest>=6.2.5",
        "black>=21.7b0",
        "flake8>=3.9.0",
        "mypy>=0.910",
        "yfinance>=0.1.70",
        "statsmodels>=0.13.0",
        "arch>=5.0.0",
        "cvxpy>=1.2.0",
        "pymoo>=0.5.0"
    ],
    python_requires=">=3.8",
    author="Deluair",
    author_email="deluair@example.com",
    description="Autonomous Portfolio Management and Trading Infrastructure",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/deluair/Autonomous-Portfolio-Management-and-Trading-Infrastructure",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
) 